### PR TITLE
Added USE_DEST_DATE_FOLDER to create individual folders

### PR DESCRIPTION
**Pull request by valdearg**
I like to make backups into dated folders, so /dest_folder/container_name/date (2024-04-05)

Maybe needs another one for date format? Might be useful to someone.

### CODE REVIEW

**Comment by Minituff** [comment]
Hey thanks for submitting a PR, this is a a good idea. I do think we might as well add a Date formatting option as well. I'll see if I can find some time to add that as well as a few unit tests. Once we get that in, I'd love to merge this in. Hopefully I can find some time soon to work on it, it shouldn't be much extra work.

**Comment by Minituff** [comment]
I'm going to merge this into a new branch called `create-dated-destination-folder` that I'll start adding to.

**Comment by Minituff** [comment]
Also tagging you in the updated PR, feel free to contribute if you'd like.
https://github.com/Minituff/nautical-backup/pull/217

**Comment by Minituff** [comment]
This has been added in the [latest release](https://github.com/Minituff/nautical-backup/releases/tag/v2.3.0).

Check out the [Environment Variables](https://minituff.github.io/nautical-backup/arguments/), you will have to do a little bit of configuration to get the results you requested originally in your PR, but the functionality is there.

**Comment by valdearg** [comment]
Looks great, thanks so much for adding that in!

**Pull request merged**
